---
title: "Notebook for Garret so he can save me"
output: html_notebook
---

---
title: "R Notebook"
output: html_notebook
---

```{r setup, message = FALSE}
library(quantmod)
library(tidyverse)
library(PerformanceAnalytics)
library(tidyquant)
library(purrr)
```


```{r}

symbols <- c("SPY","IJS","EFA","EEM","IEF")

prices <- 
  getSymbols(symbols, src = 'google', from = "2017-01-01", 
             auto.assign = TRUE, warnings = FALSE) %>% 
  map(~Cl(get(.))) %>% 
  reduce(merge) %>%
  `colnames<-`(symbols)

# generate daily return series for funds
returns <-na.omit(ROC(prices, 1, "continuous"))
```


```{r}
# Before we get to substance, let's convert the xts returns to a tibble. 

returns_df <- returns %>% 
  as_tibble(preserve_row_names = TRUE) %>% 
  mutate(date = ymd(row.names)) %>% 
  select(-row.names) %>% 
  select(date, everything())
```

```{r Function to calculate SD at intervals}

# calculate risk contribution to portfolio with function from PortfolioAnalytics package

my_interval_sd <- function(returns_df = returns_df, start = 1, window = 20){
  
  # First create start date
  start_date = returns_df$date[start]
  
  # Next an end date
  end_date = returns_df$date[c(start + window)]
  
  # Filter on start and end date
  interval_to_use <- returns_df %>% filter(date >= start_date & date < end_date)
  
  # Convert to xts so can use built in Performance Analytics function.
  returns_xts <- interval_to_use %>% as_xts(date_col = date) 
  
  # Portfolio weights.
  w <- c(0.25, 0.20, 0.15, 0.15, 0.25)
  
  # Pass xts object to function.
  results_as_xts <- StdDev(returns_xts, weights = w, portfolio_method = "component")
  
  # Convert results to tibble.
  results_to_tibble <- as_tibble(t(results_as_xts$pct_contrib_StdDev)) %>% 
    mutate(`end date` = end_date) %>% 
    select(`end date`, everything()) 
}
```


```{r Apply function by hand}
# Brute force this function starting at row 1 and going through 5. 
# Can't figure out how to map! 

rolling_sd_test1 <- my_interval_sd(returns_df, 1, 20)
rolling_sd_test2 <- my_interval_sd(returns_df, 2, 20)
rolling_sd_test3 <- my_interval_sd(returns_df, 3, 20)
rolling_sd_test4 <- my_interval_sd(returns_df, 4, 20)
rolling_sd_test5 <- my_interval_sd(returns_df, 5, 20)

bound <- bind_rows(rolling_sd_test1, rolling_sd_test2, rolling_sd_test3, rolling_sd_test4, rolling_sd_test5)
library

window <- 20

test <- map_df(1:(nrow(returns_df)-window), my_interval_sd, returns_df = returns_df, window = window)


```














